# Generated by Django 3.2.5 on 2021-07-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='nombres',
            field=models.CharField(max_length=40, verbose_name='Nombres'),
        ),
    ]
