# Generated by Django 3.2.4 on 2021-06-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='netdevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccionip', models.CharField(max_length=40)),
                ('protocolo', models.CharField(max_length=15)),
                ('puerto', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
