# Generated by Django 3.2.4 on 2021-06-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napalmweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netdevice',
            name='direccionip',
            field=models.CharField(max_length=40, verbose_name='Direccion IP'),
        ),
        migrations.AlterField(
            model_name='netdevice',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password '),
        ),
        migrations.AlterField(
            model_name='netdevice',
            name='protocolo',
            field=models.CharField(max_length=15, verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='netdevice',
            name='puerto',
            field=models.EmailField(max_length=200, verbose_name='No. Puerto'),
        ),
    ]
