# Generated by Django 3.2.4 on 2021-06-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napalmweb', '0002_auto_20210629_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netdevice',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
    ]
