# Generated by Django 3.2.4 on 2021-06-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napalmweb', '0004_auto_20210629_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netdevice',
            name='puerto',
            field=models.CharField(max_length=5),
        ),
    ]
