# Generated by Django 3.2.4 on 2021-07-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napalmweb', '0005_alter_netdevice_puerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='netdevice',
            name='usuario',
            field=models.CharField(null=True, default=None, max_length=40),
        ),
    ]
